#pragma warning disable IDE0060, IDE0059, SA1313
namespace AzureFunctionsExtension.Generator;

using AzureFunctionsExtension.Generator.Models;

using SourceGenerateHelper;

internal static class FunctionSourceBuilder
{
    // ReSharper disable InconsistentNaming
    private const string FunctionAttributeType = "global::Microsoft.Azure.Functions.Worker.Function";
    private const string HttpTriggerType = "global::Microsoft.Azure.Functions.Worker.HttpTrigger";
    private const string TimerTriggerType = "global::Microsoft.Azure.Functions.Worker.TimerTrigger";
    private const string QueueTriggerType = "global::Microsoft.Azure.Functions.Worker.QueueTrigger";
    private const string HttpRequestType = "global::Microsoft.AspNetCore.Http.HttpRequest";
    private const string FunctionContextType = "global::Microsoft.Azure.Functions.Worker.FunctionContext";
    private const string TimerInfoType = "global::Microsoft.Azure.Functions.Worker.TimerInfo";
    private const string IActionResultType = "global::Microsoft.AspNetCore.Mvc.IActionResult";
    private const string BadRequestResultType = "global::Microsoft.AspNetCore.Mvc.BadRequestObjectResult";
    private const string ObjectResultType = "global::Microsoft.AspNetCore.Mvc.ObjectResult";
    private const string StatusCodeResultType = "global::Microsoft.AspNetCore.Mvc.StatusCodeResult";
    private const string ResultsType = "global::AzureFunctionsExtension.Results";
    private const string InvocationContextType = "global::AzureFunctionsExtension.Filters.FunctionInvocationContext";
    private const string FilterDelegateType = "global::AzureFunctionsExtension.Filters.FunctionFilterDelegate";
    private const string BodySerializerType = "global::AzureFunctionsExtension.Serialization.IBodySerializer";
    private const string DefaultBodySerializerType = "global::AzureFunctionsExtension.Serialization.JsonBodySerializer";
    private const string RequestValidatorType = "global::AzureFunctionsExtension.Validation.IRequestValidator";
    private const string DefaultRequestValidatorType = "global::AzureFunctionsExtension.Validation.DataAnnotationsRequestValidator";
    private const string ApiExceptionType = "global::AzureFunctionsExtension.ApiException";
    private const string JsonExceptionType = "global::System.Text.Json.JsonException";
    private const string StringConverterType = "global::AzureFunctionsExtension.Binders.StringConverter";
    private const string GetRequiredService = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";
    private const string GetRequiredKeyedService = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService";
    private const string GetService = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService";
    private const string ActivatorUtilitiesType = "global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities";
    private const string GetLoggerMethod = "global::Microsoft.Azure.Functions.Worker.FunctionContextLoggerExtensions.GetLogger";
    private const string LogErrorMethod = "global::Microsoft.Extensions.Logging.LoggerExtensions.LogError";
    private const string AsSpanMethod = "global::System.MemoryExtensions.AsSpan";
    // ReSharper restore InconsistentNaming

    // クラス全体で共有する静的フィールド (target/provider/serializer/filter など) を含む
    // __shared__ ファイルを生成する。
    // Generates the __shared__ file containing static fields shared across all handlers
    // (target instance, service provider, serializer, validator, filters).
    public static void BuildShared(SourceBuilder builder, FunctionModel model)
    {
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        var classKeyword = model.IsValueType ? "struct" : "class";
        builder.AppendLine($"partial {classKeyword} {model.ClassName}");
        builder.BeginBlock();
        builder.EndBlock();
    }

    // 1 ハンドラーに対応する部分クラスファイルを生成する。
    // フィルターが存在する場合は InnerMethod + Pipeline を先に出力し、
    // その後にエントリーポイントとなる HandlerMethod を出力する。
    // Generates a partial class file for one handler.
    // When filters exist, emits InnerMethod + Pipeline before the entry-point HandlerMethod.
    public static void Build(SourceBuilder builder, FunctionModel model, HandlerModel handler)
    {
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        var classKeyword = model.IsValueType ? "struct" : "class";
        builder.AppendLine($"partial {classKeyword} {model.ClassName}");
        builder.BeginBlock();

        if (model.Filters.Count > 0)
        {
            // フィルターがある場合：InnerMethod (実処理) とパイプラインを生成してから HandlerMethod を出力する
            // With filters: emit InnerMethod (actual logic) and pipeline, then the HandlerMethod entry point
            BuildInnerMethod(builder, model, handler);
            builder.NewLine();
            BuildPipeline(builder, model, handler);
            builder.NewLine();
        }

        BuildHandlerMethod(builder, model, handler);

        builder.EndBlock();
    }

    // フィルターパイプラインから呼ばれる Inner メソッドを生成する。
    // FunctionInvocationContext 経由でリクエストを受け取り、パラメータバインドと実メソッド呼び出しを行う。
    // Generates the inner method called by the filter pipeline.
    // Receives the request via FunctionInvocationContext, binds parameters, and invokes the actual handler.
    private static void BuildInnerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler)
    {
        builder.AppendLine($"private static async global::System.Threading.Tasks.ValueTask __{handler.MethodName}_Inner__(");
        builder.AppendLine($"    {InvocationContextType} ctx,");
        builder.AppendLine("    global::System.IServiceProvider services,");
        builder.AppendLine($"    {model.FunctionType.FullName} target)");
        builder.BeginBlock();

        if (handler.Type == HandlerType.Http)
        {
            // ctx.Request を HttpRequest にキャストして req 変数として取り出す
            // Cast ctx.Request to HttpRequest and expose it as req
            builder.AppendLine($"var req = ({HttpRequestType})ctx.Request!;");
            builder.NewLine();
        }
        else if (handler.Type == HandlerType.Timer)
        {
            builder.AppendLine($"var timerInfo = ({TimerInfoType})ctx.Request!;");
            builder.NewLine();
        }
        else if (handler.Type == HandlerType.Queue)
        {
            builder.AppendLine("var message = (string)ctx.Request!;");
            builder.NewLine();
        }

        BuildParameterBindings(builder, handler, hasFilter: true);
        BuildHandlerInvocation(builder, handler, hasFilter: true);

        builder.EndBlock();
    }

    // フィルターを逆順に合成してミドルウェアパイプラインを構築する静的フィールドとファクトリメソッドを生成する。
    // InnerMethod を末端として、外側のフィルターから順に包み込む形で delegate チェーンを作る。
    // Generates a static pipeline field and factory method that compose filters in reverse order,
    // wrapping the InnerMethod as the terminal delegate to form a middleware chain.
    private static void BuildPipeline(SourceBuilder builder, FunctionModel model, HandlerModel handler)
    {
        var pascal = ToPascalCase(handler.MethodName);
        builder.AppendLine($"private static {FilterDelegateType} Build{pascal}Pipeline(");
        builder.AppendLine("    global::System.IServiceProvider services,");
        builder.AppendLine($"    {model.FunctionType.FullName} target)");
        builder.BeginBlock();

        var filters = model.Filters;
        // Inner メソッドをパイプラインの末端 (terminal) として設定する
        // Set the inner method as the terminal of the pipeline
        builder.AppendLine($"{FilterDelegateType} p = ctx => __{handler.MethodName}_Inner__(ctx, services, target);");
        builder.NewLine();

        // 末尾のフィルターから先頭に向かって順に delegate を包み込む (onion model)
        // Wrap delegates from the last filter toward the first (onion model)
        for (var i = filters.Count - 1; i >= 0; i--)
        {
            var filterType = filters[i].FullName;
            builder.AppendLine($"var inner{i} = p;");
            builder.AppendLine($"var filter{i} = {GetService}<{filterType}>(services) ??");
            builder.AppendLine($"    {ActivatorUtilitiesType}.CreateInstance<{filterType}>(services);");
            builder.AppendLine($"p = ctx => filter{i}.InvokeAsync(ctx, inner{i});");
            if (i > 0)
            {
                builder.NewLine();
            }
        }

        builder.NewLine();
        builder.AppendLine("return p;");
        builder.EndBlock();
    }

    // [Function] 属性を付与したエントリーポイントメソッドをハンドラーの種類に応じて振り分けて生成する。
    // Generates the [Function]-attributed entry-point method, dispatching to the appropriate builder
    // based on handler kind (Http / Timer / Queue).
    private static void BuildHandlerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler)
    {
        builder.AppendLine($"[{FunctionAttributeType}(\"{handler.MethodName}\")]");

        switch (handler.Type)
        {
            case HandlerType.Http:
                BuildHttpHandlerMethod(builder, model, handler, model.Filters.Count > 0);
                break;
            case HandlerType.Timer:
                BuildTimerHandlerMethod(builder, model, handler, model.Filters.Count > 0);
                break;
            case HandlerType.Queue:
                BuildQueueHandlerMethod(builder, model, handler, model.Filters.Count > 0);
                break;
        }
    }

    // HTTP トリガー向けエントリーポイントを生成する。
    // フィルターあり: InvocationContext を作成してパイプラインに委譲し、ApiException / Exception を補足して適切な IActionResult を返す。
    // フィルターなし: 直接パラメータバインドと呼び出しを行い、例外をハンドリングする。
    // Generates an HTTP trigger entry-point.
    // With filters: creates InvocationContext, delegates to the pipeline, and catches ApiException/Exception.
    // Without filters: binds parameters and invokes directly with exception handling.
    private static void BuildHttpHandlerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler, bool hasFilters)
    {
        var authLevel = $"global::Microsoft.Azure.Functions.Worker.AuthorizationLevel.{handler.AuthorizationLevel ?? "Function"}";
        var httpMethod = handler.HttpMethod ?? "get";
        var route = handler.Route ?? handler.MethodName;

        builder.AppendLine($"public static async global::System.Threading.Tasks.Task<{IActionResultType}> {handler.MethodName}_Handler(");
        builder.AppendLine($"    [{HttpTriggerType}({authLevel}, \"{httpMethod}\", Route = \"{route}\")] {HttpRequestType} req,");
        builder.AppendLine($"    {FunctionContextType} context)");
        builder.BeginBlock();

        BuildInvocationSetup(builder, model);
        builder.NewLine();

        if (hasFilters)
        {
            builder.AppendLine($"var ctx = new {InvocationContextType}");
            builder.BeginBlock();
            builder.AppendLine("Request = req,");
            builder.AppendLine("FunctionContext = context,");
            builder.AppendLine("CancellationToken = context.CancellationToken,");
            builder.EndBlock(semicolon: true);
            builder.AppendLine($"var pipeline = Build{ToPascalCase(handler.MethodName)}Pipeline(services, target);");
            builder.NewLine();

            builder.AppendLine("try");
            builder.BeginBlock();
            builder.AppendLine("await pipeline(ctx);");
            builder.EndBlock();
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            builder.AppendLine($"return new {ObjectResultType}(ex.Message) {{ StatusCode = ex.StatusCode }};");
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine($"{LogErrorMethod}({GetLoggerMethod}(context, context.FunctionDefinition.Name), ex, ex.Message);");
            builder.AppendLine($"return new {StatusCodeResultType}(500);");
            builder.EndBlock();
            builder.NewLine();
            builder.AppendLine($"return ({IActionResultType})ctx.Result!;");
        }
        else
        {
            builder.AppendLine("try");
            builder.BeginBlock();
            BuildParameterBindings(builder, handler, hasFilter: false);
            BuildHandlerInvocation(builder, handler, hasFilter: false);
            builder.EndBlock();
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            builder.AppendLine($"return new {ObjectResultType}(ex.Message) {{ StatusCode = ex.StatusCode }};");
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine($"{LogErrorMethod}({GetLoggerMethod}(context, context.FunctionDefinition.Name), ex, ex.Message);");
            builder.AppendLine($"return new {StatusCodeResultType}(500);");
            builder.EndBlock();
        }

        builder.EndBlock();
    }

    // タイマートリガー向けエントリーポイントを生成する。
    // フィルターあり: InvocationContext 経由でパイプラインに委譲。
    // フィルターなし: FromServices パラメータを解決して直接呼び出す。
    // Generates a Timer trigger entry-point.
    // With filters: delegates to the pipeline via InvocationContext.
    // Without filters: resolves FromServices parameters and invokes directly.
    private static void BuildTimerHandlerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler, bool hasFilters)
    {
        var schedule = handler.TimerSchedule ?? "0 * * * * *";

        builder.AppendLine($"public static async global::System.Threading.Tasks.Task {handler.MethodName}_Handler(");
        builder.AppendLine($"    [{TimerTriggerType}(\"{schedule}\")] {TimerInfoType} timerInfo,");
        builder.AppendLine($"    {FunctionContextType} context)");
        builder.BeginBlock();

        BuildInvocationSetup(builder, model);
        builder.NewLine();

        if (hasFilters)
        {
            builder.AppendLine($"var ctx = new {InvocationContextType}");
            builder.BeginBlock();
            builder.AppendLine("Request = timerInfo,");
            builder.AppendLine("FunctionContext = context,");
            builder.AppendLine("CancellationToken = context.CancellationToken,");
            builder.EndBlock(semicolon: true);
            builder.AppendLine($"var pipeline = Build{ToPascalCase(handler.MethodName)}Pipeline(services, target);");
            builder.NewLine();
            builder.AppendLine("try");
            builder.BeginBlock();
            builder.AppendLine("await pipeline(ctx);");
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine($"{LogErrorMethod}({GetLoggerMethod}(context, context.FunctionDefinition.Name), ex, ex.Message);");
            builder.AppendLine("throw;");
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine("try");
            builder.BeginBlock();
            BuildTimerParameterBindings(builder, handler);
            BuildHandlerInvocation(builder, handler, hasFilter: false);
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine($"{LogErrorMethod}({GetLoggerMethod}(context, context.FunctionDefinition.Name), ex, ex.Message);");
            builder.AppendLine("throw;");
            builder.EndBlock();
        }

        builder.EndBlock();
    }

    // キュートリガー向けエントリーポイントを生成する。
    // フィルターあり: InvocationContext 経由でパイプラインに委譲。
    // フィルターなし: FromServices パラメータを解決して直接呼び出す。
    // Generates a Queue trigger entry-point.
    // With filters: delegates to the pipeline via InvocationContext.
    // Without filters: resolves FromServices parameters and invokes directly.
    private static void BuildQueueHandlerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler, bool hasFilters)
    {
        var queueName = handler.QueueName ?? "myqueue";
        var connectionPart = handler.QueueConnection is not null ? $", Connection = \"{handler.QueueConnection}\"" : string.Empty;

        builder.AppendLine($"public static async global::System.Threading.Tasks.Task {handler.MethodName}_Handler(");
        builder.AppendLine($"    [{QueueTriggerType}(\"{queueName}\"{connectionPart})] string message,");
        builder.AppendLine($"    {FunctionContextType} context)");
        builder.BeginBlock();

        BuildInvocationSetup(builder, model);
        builder.NewLine();

        if (hasFilters)
        {
            builder.AppendLine($"var ctx = new {InvocationContextType}");
            builder.BeginBlock();
            builder.AppendLine("Request = message,");
            builder.AppendLine("FunctionContext = context,");
            builder.AppendLine("CancellationToken = context.CancellationToken,");
            builder.EndBlock(semicolon: true);
            builder.AppendLine($"var pipeline = Build{ToPascalCase(handler.MethodName)}Pipeline(services, target);");
            builder.NewLine();
            builder.AppendLine("try");
            builder.BeginBlock();
            builder.AppendLine("await pipeline(ctx);");
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine($"{LogErrorMethod}({GetLoggerMethod}(context, context.FunctionDefinition.Name), ex, ex.Message);");
            builder.AppendLine("throw;");
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine("try");
            builder.BeginBlock();
            BuildQueueParameterBindings(builder, handler);
            BuildHandlerInvocation(builder, handler, hasFilter: false);
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine($"{LogErrorMethod}({GetLoggerMethod}(context, context.FunctionDefinition.Name), ex, ex.Message);");
            builder.AppendLine("throw;");
            builder.EndBlock();
        }

        builder.EndBlock();
    }

    // HTTP ハンドラーの全パラメータに対してバインディングコードを順に出力する。
    // Emits binding code for all parameters of an HTTP handler in order.
    private static void BuildParameterBindings(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        var parameters = handler.Parameters;
        for (var i = 0; i < parameters.Count; i++)
        {
            BuildParameterBinding(builder, parameters[i], i, hasFilter);
        }
    }

    // タイマーハンドラーで FromServices パラメータのみ DI から解決するコードを出力する。
    // Emits DI resolution code only for FromServices parameters in a Timer handler.
    private static void BuildTimerParameterBindings(SourceBuilder builder, HandlerModel handler)
    {
        var parameters = handler.Parameters;
        for (var i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            if (p.BindingType == ParameterBindingType.FromServices)
            {
                builder.AppendLine($"var p{i} = {ResolveServiceExpression(p.Type.FullName, p.Key)};");
                builder.NewLine();
            }
        }
    }

    // [FromServices] のキー指定有無に応じて非キー付き／キー付き DI 解決式を生成する。
    // Builds a non-keyed or keyed DI resolution expression depending on the [FromServices] key.
    private static string ResolveServiceExpression(string typeName, string key) =>
        String.IsNullOrEmpty(key)
            ? $"{GetRequiredService}<{typeName}>(services)"
            : $"{GetRequiredKeyedService}<{typeName}>(services, \"{key}\")";

    // キューハンドラーで FromServices パラメータのみ DI から解決するコードを出力する。
    // Emits DI resolution code only for FromServices parameters in a Queue handler.
    private static void BuildQueueParameterBindings(SourceBuilder builder, HandlerModel handler)
    {
        var parameters = handler.Parameters;
        for (var i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            if (p.BindingType == ParameterBindingType.FromServices)
            {
                builder.AppendLine($"var p{i} = {ResolveServiceExpression(p.Type.FullName, p.Key)};");
                builder.NewLine();
            }
        }
    }

    // 1 つのパラメータについてバインディング種別に応じたコードを出力する。
    // HttpRequest / FunctionContext / CancellationToken / Logger は呼び出し時に直接渡すためスキップ。
    // FromServices は DI 解決、FromBody はデシリアライズ＋バリデーション、
    // FromQuery / FromRoute / FromHeader は文字列変換を経由して代入する。
    // Emits binding code for a single parameter based on its binding kind.
    // HttpRequest / FunctionContext / CancellationToken / Logger are passed directly at call site, so skipped here.
    // FromServices: DI resolution. FromBody: deserialize + validate.
    // FromQuery / FromRoute / FromHeader: string conversion then assignment.
    private static void BuildParameterBinding(SourceBuilder builder, ParameterModel param, int index, bool hasFilter)
    {
        var pVar = $"p{index}";
        var typeName = param.Type.FullName;

        switch (param.BindingType)
        {
            case ParameterBindingType.HttpRequest:
            case ParameterBindingType.FunctionContext:
            case ParameterBindingType.CancellationToken:
            case ParameterBindingType.Logger:
                return;
            case ParameterBindingType.FromServices:
                builder.AppendLine($"var {pVar} = {ResolveServiceExpression(typeName, param.Key)};");
                builder.NewLine();
                return;
            case ParameterBindingType.FromBody:
                builder.AppendLine($"var bodySerializer{index} = {GetService}<{BodySerializerType}>(services) ?? {DefaultBodySerializerType}.Default;");
                builder.AppendLine($"var {pVar} = default({typeName})!;");
                builder.AppendLine("try");
                builder.BeginBlock();
                builder.AppendLine($"{pVar} = bodySerializer{index}.Deserialize<{typeName}>(req.Body);");
                builder.EndBlock();
                builder.AppendLine($"catch ({JsonExceptionType})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}(\"Invalid request body.\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}(\"Invalid request body.\");");
                }
                builder.EndBlock();
                if (!IsNullableBodyParameter(param))
                {
                    builder.AppendLine($"if ({pVar} is null)");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = new {BadRequestResultType}(\"Request body is required.\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine($"return new {BadRequestResultType}(\"Request body is required.\");");
                    }
                    builder.EndBlock();
                }

                if (!param.SkipValidation)
                {
                    builder.AppendLine($"var requestValidator{index} = {GetService}<{RequestValidatorType}>(services) ?? new {DefaultRequestValidatorType}();");
                    builder.AppendLine($"if ({pVar} is not null && !requestValidator{index}.Validate({pVar}))");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = new {BadRequestResultType}(\"Validation failed: {param.Name}\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine($"return new {BadRequestResultType}(\"Validation failed: {param.Name}\");");
                    }
                    builder.EndBlock();
                }

                builder.NewLine();
                return;
            case ParameterBindingType.FromQuery:
                BuildScalarOrArrayBinding(builder, param, index, hasFilter, "req.Query");
                return;
            case ParameterBindingType.FromRoute:
                BuildRouteBinding(builder, param, index, hasFilter);
                return;
            case ParameterBindingType.FromHeader:
                BuildHeaderBinding(builder, param, index, hasFilter);
                return;
        }
    }

    // クエリ文字列またはヘッダー辞書から値を取り出し、スカラー / 配列 / Nullable のいずれかに変換するコードを出力する。
    // 変換失敗時は BadRequest を返す (hasFilter の場合は ctx.Result にセットして return)。
    // Emits code to extract a value from a query/header dictionary and convert it to scalar, array, or Nullable.
    // On conversion failure, returns BadRequest (or sets ctx.Result and returns when hasFilter is true).
    private static void BuildScalarOrArrayBinding(SourceBuilder builder, ParameterModel param, int index, bool hasFilter, string dictExpr)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var typeName = param.Type.FullName;
        var key = param.Key;
        var defaultLiteral = param.HasDefault ? (param.DefaultValueLiteral ?? "default") : null;

        if (param.Type.IsArray && (param.Type.ElementType is not null))
        {
            var elemType = param.Type.ElementType.FullName;
            var converterMethod = param.ConverterMethod;
            builder.AppendLine($"var {pVar} = global::System.Array.Empty<{elemType}>();");
            builder.AppendLine($"if ({dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
            builder.BeginBlock();
            builder.AppendLine($"var {pVar}parts = {pRaw}.ToString().Split(',');");
            builder.AppendLine($"{pVar} = new {elemType}[{pVar}parts.Length];");
            builder.AppendLine($"for (var i = 0; i < {pVar}parts.Length; i++)");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar}[i] = {pVar}parts[i];");
            }
            else if (param.Type.ElementType.IsNullable && (param.Type.ElementType.UnderlyingType is not null))
            {
                var baseElemType = param.Type.ElementType.UnderlyingType.FullName;
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{baseElemType}>({AsSpanMethod}({pVar}parts[i]), out var {pVar}elem)"
                    : $"!{StringConverterType}.{converterMethod}({AsSpanMethod}({pVar}parts[i]), out var {pVar}elem)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar}[i] = {pVar}elem;");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{elemType}>({AsSpanMethod}({pVar}parts[i]), out {pVar}[i])"
                    : $"!{StringConverterType}.{converterMethod}({AsSpanMethod}({pVar}parts[i]), out {pVar}[i])";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
            }

            builder.EndBlock();
            builder.EndBlock();
            builder.NewLine();
        }
        else if (param.Type.IsNullable && (param.Type.UnderlyingType is not null))
        {
            var baseType = param.Type.UnderlyingType.FullName;
            var converterMethod = param.ConverterMethod;
            var init = defaultLiteral is not null ? $"({typeName}){defaultLiteral}" : $"({typeName})null";
            builder.AppendLine($"var {pVar} = {init};");
            builder.AppendLine($"if ({dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw};");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{baseType}>({AsSpanMethod}({pRaw}.ToString()), out var {pVar}tmp)"
                    : $"!{StringConverterType}.{converterMethod}({AsSpanMethod}({pRaw}.ToString()), out var {pVar}tmp)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar} = {pVar}tmp;");
            }

            builder.EndBlock();
            builder.NewLine();
        }
        else
        {
            var converterMethod = param.ConverterMethod;
            if (String.IsNullOrEmpty(converterMethod))
            {
                var init = defaultLiteral is not null ? $"({typeName}){defaultLiteral}!" : $"default({typeName})!";
                builder.AppendLine($"var {pVar} = {init};");
                builder.AppendLine($"if ({dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
                builder.AppendLine($"    {pRaw} != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
                builder.BeginBlock();
                builder.AppendLine($"{pVar} = {pRaw}!;");
                builder.EndBlock();
                builder.NewLine();
            }
            else
            {
                var init = defaultLiteral is not null ? $"({typeName}){defaultLiteral}" : $"default({typeName})";
                builder.AppendLine($"var {pVar} = {init};");
                builder.AppendLine($"if ({dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
                builder.AppendLine($"    {pRaw} != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
                builder.BeginBlock();
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{typeName}>({AsSpanMethod}({pRaw}.ToString()), out {pVar})"
                    : $"!{StringConverterType}.{converterMethod}({AsSpanMethod}({pRaw}.ToString()), out {pVar})";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
                builder.EndBlock();
                builder.NewLine();
            }
        }
    }

    // RouteValues からルートパラメータを取り出して型変換するコードを出力する。
    // Emits code to extract and convert a route parameter from RouteValues.
    private static void BuildRouteBinding(SourceBuilder builder, ParameterModel param, int index, bool hasFilter)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var typeName = param.Type.FullName;
        var key = param.Key;
        var converterMethod = param.ConverterMethod;
        var defaultLiteral = param.HasDefault ? (param.DefaultValueLiteral ?? "default") : null;

        if (param.Type.IsNullable && (param.Type.UnderlyingType is not null))
        {
            var baseType = param.Type.UnderlyingType.FullName;
            var init = defaultLiteral is not null ? $"({typeName}){defaultLiteral}" : $"({typeName})null";
            builder.AppendLine($"var {pVar} = {init};");
            builder.AppendLine($"if (req.RouteValues.TryGetValue(\"{key}\", out var {pRaw}obj) && {pRaw}obj is string {pRaw})");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw};");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{baseType}>({AsSpanMethod}({pRaw}), out var {pVar}tmp)"
                    : $"!{StringConverterType}.{converterMethod}({AsSpanMethod}({pRaw}), out var {pVar}tmp)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar} = {pVar}tmp;");
            }

            builder.EndBlock();
            builder.NewLine();
        }
        else
        {
            var init = defaultLiteral is not null ? $"({typeName}){defaultLiteral}" : $"default({typeName})";
            builder.AppendLine($"var {pVar} = {init};");
            builder.AppendLine($"if (req.RouteValues.TryGetValue(\"{key}\", out var {pRaw}obj) && {pRaw}obj is string {pRaw})");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw}!;");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{typeName}>({AsSpanMethod}({pRaw}), out {pVar})"
                    : $"!{StringConverterType}.{converterMethod}({AsSpanMethod}({pRaw}), out {pVar})";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
            }

            builder.EndBlock();
            builder.NewLine();
        }
    }

    // リクエストヘッダーから値を取り出して型変換するコードを出力する。
    // Emits code to extract and convert a value from the request Headers collection.
    private static void BuildHeaderBinding(SourceBuilder builder, ParameterModel param, int index, bool hasFilter)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var typeName = param.Type.FullName;
        var key = param.Key;
        var converterMethod = param.ConverterMethod;
        var defaultLiteral = param.HasDefault ? (param.DefaultValueLiteral ?? "default") : null;

        if (param.Type.IsNullable && (param.Type.UnderlyingType is not null))
        {
            var baseType = param.Type.UnderlyingType.FullName;
            var init = defaultLiteral is not null ? $"({typeName}){defaultLiteral}" : $"({typeName})null";
            builder.AppendLine($"var {pVar} = {init};");
            builder.AppendLine($"if (req.Headers.TryGetValue(\"{key}\", out var {pRaw}sv) &&");
            builder.AppendLine($"    {pRaw}sv != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
            builder.BeginBlock();
            builder.AppendLine($"var {pRaw} = {pRaw}sv.ToString();");
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw};");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{baseType}>({AsSpanMethod}({pRaw}), out var {pVar}tmp)"
                    : $"!{StringConverterType}.{converterMethod}({AsSpanMethod}({pRaw}), out var {pVar}tmp)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar} = {pVar}tmp;");
            }

            builder.EndBlock();
            builder.NewLine();
        }
        else
        {
            var init = String.IsNullOrEmpty(converterMethod)
                ? (defaultLiteral is not null ? $"({typeName}){defaultLiteral}!" : $"default({typeName})!")
                : (defaultLiteral is not null ? $"({typeName}){defaultLiteral}" : $"default({typeName})");
            builder.AppendLine($"var {pVar} = {init};");
            builder.AppendLine($"if (req.Headers.TryGetValue(\"{key}\", out var {pRaw}sv) &&");
            builder.AppendLine($"    {pRaw}sv != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
            builder.BeginBlock();
            builder.AppendLine($"var {pRaw} = {pRaw}sv.ToString();");
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw}!;");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{typeName}>({AsSpanMethod}({pRaw}), out {pVar})"
                    : $"!{StringConverterType}.{converterMethod}({AsSpanMethod}({pRaw}), out {pVar})";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
            }

            builder.EndBlock();
            builder.NewLine();
        }
    }

    // __target__ の実メソッドを呼び出すコードを出力する。
    // HTTP の戻り値は IActionResult ならそのまま、void / Task は Results.Ok()、それ以外は Results.Ok(value) でラップする。
    // Results.Ok を経由することでライブラリ独自の JsonOptions が適用される。
    // 結果はフィルターモードなら ctx.Result に、直接モードなら return に使う。
    // Emits code to invoke the actual method on __target__.
    // For HTTP, an IActionResult is returned as-is; void/Task is wrapped as Results.Ok() and any other
    // return value as Results.Ok(value), so the library's JsonOptions is honored.
    // The result is assigned to ctx.Result in filter mode, otherwise returned.
    private static void BuildHandlerInvocation(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        var args = BuildCallArgs(handler, hasFilter);
        var awaitPrefix = handler.IsAsync ? "await " : string.Empty;

        if (handler.Type != HandlerType.Http)
        {
            if (handler.ResultType is not null)
            {
                builder.AppendLine($"var __result__ = {awaitPrefix}target.{handler.MethodName}({args});");
                if (hasFilter)
                {
                    builder.AppendLine("ctx.Result = __result__;");
                }
            }
            else
            {
                builder.AppendLine($"{awaitPrefix}target.{handler.MethodName}({args});");
            }

            return;
        }

        // 戻り値なし (void / Task / ValueTask) は実行後に 200 OK を返す
        // No return value (void / Task / ValueTask): invoke then return 200 OK
        if (handler.ResultType is null)
        {
            builder.AppendLine($"{awaitPrefix}target.{handler.MethodName}({args});");
            EmitHttpResult(builder, $"{ResultsType}.Ok()", hasFilter);
            return;
        }

        // IActionResult はそのまま、それ以外の戻り値は Results.Ok でラップする
        // Return IActionResult as-is; wrap any other return value with Results.Ok
        builder.AppendLine($"var __result__ = {awaitPrefix}target.{handler.MethodName}({args});");
        var resultExpr = handler.ResultIsActionResult ? "__result__" : $"{ResultsType}.Ok(__result__)";
        EmitHttpResult(builder, resultExpr, hasFilter);
    }

    // HTTP ハンドラーの結果を、フィルターモードなら ctx.Result へ、直接モードなら return で返す。
    // Emits the HTTP handler result: assigns to ctx.Result in filter mode, otherwise returns it.
    private static void EmitHttpResult(SourceBuilder builder, string resultExpr, bool hasFilter)
    {
        builder.AppendLine(hasFilter ? $"ctx.Result = {resultExpr};" : $"return {resultExpr};");
    }

    // 各パラメータのバインディング種別に応じた呼び出し引数式の文字列を組み立てる。
    // Builds the comma-separated argument expression string for each parameter based on its binding kind.
    private static string BuildCallArgs(HandlerModel handler, bool hasFilter)
    {
        var parameters = handler.Parameters;
        var argParts = new List<string>();

        for (var i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            switch (p.BindingType)
            {
                case ParameterBindingType.HttpRequest:
                    argParts.Add("req");
                    break;
                case ParameterBindingType.FunctionContext:
                    argParts.Add(hasFilter ? "ctx.FunctionContext" : "context");
                    break;
                case ParameterBindingType.CancellationToken:
                    argParts.Add(hasFilter ? "ctx.CancellationToken" : "context.CancellationToken");
                    break;
                case ParameterBindingType.Logger:
                    argParts.Add($"{GetRequiredService}<{p.Type.FullName}>(services)");
                    break;
                case ParameterBindingType.FromTrigger:
                    argParts.Add(handler.Type == HandlerType.Timer ? "timerInfo" : "message");
                    break;
                default:
                    argParts.Add($"p{i}!");
                    break;
            }
        }

        return String.Join(", ", argParts);
    }

    private static void BuildInvocationSetup(SourceBuilder builder, FunctionModel model)
    {
        builder.AppendLine("var services = context.InstanceServices;");
        builder.AppendLine($"var target = {ActivatorUtilitiesType}.CreateInstance<{model.FunctionType.FullName}>(services);");
    }

    private static bool IsNullableBodyParameter(ParameterModel param)
    {
        return param.Type.IsNullable || (param.Type.IsReferenceType && param.Type.IsNullableReferenceType);
    }

    private static string ToPascalCase(string name)
    {
        if (String.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }
}

internal static class SourceBuilderExtensions
{
    public static void AppendLine(this SourceBuilder builder, string line)
    {
        builder.Indent().Append(line).NewLine();
    }

    public static void BeginBlock(this SourceBuilder builder)
    {
        builder.Indent().Append("{").NewLine();
        builder.IndentLevel++;
    }

    public static void EndBlock(this SourceBuilder builder, bool semicolon = false)
    {
        builder.IndentLevel--;
        builder.Indent();
        if (semicolon)
        {
            builder.Append("};").NewLine();
        }
        else
        {
            builder.Append("}").NewLine();
        }
    }
}
