#pragma warning disable IDE0060, IDE0059, SA1313
namespace AzureFunctionsExtension.Generator;

using AzureFunctionsExtension.Generator.Models;

using SourceGenerateHelper;

internal static class WrapperBuilder
{
    private const string FunctionAttributeType = "global::Microsoft.Azure.Functions.Worker.Function";
    private const string HttpTriggerType = "global::Microsoft.Azure.Functions.Worker.HttpTrigger";
    private const string TimerTriggerType = "global::Microsoft.Azure.Functions.Worker.TimerTrigger";
    private const string QueueTriggerType = "global::Microsoft.Azure.Functions.Worker.QueueTrigger";
    private const string HttpRequestType = "global::Microsoft.AspNetCore.Http.HttpRequest";
    private const string FunctionContextType = "global::Microsoft.Azure.Functions.Worker.FunctionContext";
    private const string TimerInfoType = "global::Microsoft.Azure.Functions.Worker.TimerInfo";
    private const string IActionResultType = "global::Microsoft.AspNetCore.Mvc.IActionResult";
    private const string BadRequestResultType = "global::Microsoft.AspNetCore.Mvc.BadRequestObjectResult";
    private const string ObjectResultType = "global::Microsoft.AspNetCore.Mvc.ObjectResult";
    private const string StatusCodeResultType = "global::Microsoft.AspNetCore.Mvc.StatusCodeResult";
    private const string InvocationContextType = "global::AzureFunctionsExtension.Filters.FunctionInvocationContext";
    private const string FilterDelegateType = "global::AzureFunctionsExtension.Filters.FunctionFilterDelegate";
    private const string BodySerializerType = "global::AzureFunctionsExtension.Serialization.IBodySerializer";
    private const string RequestValidatorType = "global::AzureFunctionsExtension.Validation.IRequestValidator";
    private const string ApiExceptionType = "global::AzureFunctionsExtension.ApiException";
    private const string StringConverterType = "global::StringConvertHelper.StringConvert";
    private const string GetRequiredService = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";
    private const string BuildServiceProvider = "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider";
    private const string CancellationTokenExpr = "default(global::System.Threading.CancellationToken)";

    public static void BuildShared(SourceBuilder builder, FunctionModel model)
    {
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        var classKeyword = model.IsValueType ? "struct" : "class";
        builder.AppendLine($"partial {classKeyword} {model.ClassName}");
        builder.BeginBlock();

        BuildStaticFields(builder, model);

        builder.EndBlock();
    }

    public static void Build(SourceBuilder builder, FunctionModel model, HandlerModel handler)
    {
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        var classKeyword = model.IsValueType ? "struct" : "class";
        builder.AppendLine($"partial {classKeyword} {model.ClassName}");
        builder.BeginBlock();

        if (model.Filters.AsArray().Length > 0)
        {
            BuildInnerMethod(builder, model, handler);
            builder.NewLine();
            BuildPipeline(builder, model, handler);
            builder.NewLine();
        }

        BuildHandlerMethod(builder, model, handler);

        builder.EndBlock();
    }

    private static void BuildStaticFields(SourceBuilder builder, FunctionModel model)
    {
        var handlers = model.Handlers.AsArray();
        var hasBodyParam = handlers.Any(static h =>
            h.Parameters.AsArray().Any(static p => p.BindingKind == ParameterBindingKind.FromBody));
        var hasValidation = handlers.Any(static h =>
            h.Parameters.AsArray().Any(static p => (p.BindingKind == ParameterBindingKind.FromBody) && !p.SkipValidation));

        if (model.ServiceResolver != null)
        {
            builder.AppendLine($"private static readonly global::System.IServiceProvider __provider__ =");
            builder.AppendLine($"    {BuildServiceProvider}({model.ServiceResolver.Type.FullName}.ConfigureServices());");
            builder.NewLine();

            var ctorArgs = String.Join(", ", model.ConstructorParameters.AsArray().Select(static p => $"{GetRequiredService}<{p.FullName}>(__provider__)"));
            builder.AppendLine($"private static readonly {model.FunctionType.FullName} __target__ = new {model.FunctionType.FullName}({ctorArgs});");
        }
        else
        {
            builder.AppendLine($"private static readonly {model.FunctionType.FullName} __target__ = new {model.FunctionType.FullName}();");
        }

        if (hasBodyParam)
        {
            builder.NewLine();
            if (model.ServiceResolver != null)
            {
                builder.AppendLine($"private static readonly {BodySerializerType} __bodySerializer__ =");
                builder.AppendLine($"    {GetRequiredService}<{BodySerializerType}>(__provider__);");
            }
            else
            {
                builder.AppendLine($"private static readonly {BodySerializerType} __bodySerializer__ =");
                builder.AppendLine("    global::AzureFunctionsExtension.Serialization.JsonBodySerializer.Default;");
            }
        }

        if (hasValidation)
        {
            builder.NewLine();
            if (model.ServiceResolver != null)
            {
                builder.AppendLine($"private static readonly {RequestValidatorType} __requestValidator__ =");
                builder.AppendLine($"    {GetRequiredService}<{RequestValidatorType}>(__provider__);");
            }
            else
            {
                builder.AppendLine($"private static readonly {RequestValidatorType} __requestValidator__ =");
                builder.AppendLine("    new global::AzureFunctionsExtension.Validation.DataAnnotationsRequestValidator();");
            }
        }

        foreach (var filter in model.Filters.AsArray())
        {
            builder.NewLine();
            if (model.ServiceResolver != null)
            {
                builder.AppendLine($"private static readonly {filter.FilterType.FullName} __filter{filter.Index}__ =");
                builder.AppendLine($"    {GetRequiredService}<{filter.FilterType.FullName}>(__provider__);");
            }
            else
            {
                builder.AppendLine($"private static readonly {filter.FilterType.FullName} __filter{filter.Index}__ = new {filter.FilterType.FullName}();");
            }
        }
    }

    private static void BuildInnerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler)
    {
        builder.AppendLine($"private static async global::System.Threading.Tasks.ValueTask __{handler.MethodName}_Inner__(");
        builder.AppendLine($"    {InvocationContextType} ctx)");
        builder.BeginBlock();

        if (handler.Kind == HandlerKind.Http)
        {
            builder.AppendLine($"var req = ({HttpRequestType})ctx.Request!;");
            builder.NewLine();
        }

        BuildParameterBindings(builder, handler, hasFilter: true);
        BuildHandlerInvocation(builder, model, handler, hasFilter: true);

        builder.EndBlock();
    }

    private static void BuildPipeline(SourceBuilder builder, FunctionModel model, HandlerModel handler)
    {
        var pascal = ToPascalCase(handler.MethodName);
        builder.AppendLine($"private static readonly {FilterDelegateType} __{handler.MethodName}_Pipeline__ = Build{pascal}Pipeline();");
        builder.NewLine();
        builder.AppendLine($"private static {FilterDelegateType} Build{pascal}Pipeline()");
        builder.BeginBlock();

        var filters = model.Filters.AsArray();
        builder.AppendLine($"{FilterDelegateType} p = __{handler.MethodName}_Inner__;");
        builder.NewLine();

        for (var i = filters.Length - 1; i >= 0; i--)
        {
            var idx = filters[i].Index;
            builder.AppendLine($"var inner{i} = p;");
            builder.AppendLine($"p = ctx => __filter{idx}__.InvokeAsync(ctx, inner{i});");
            if (i > 0)
            {
                builder.NewLine();
            }
        }

        builder.NewLine();
        builder.AppendLine("return p;");
        builder.EndBlock();
    }

    private static void BuildHandlerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler)
    {
        builder.AppendLine($"[{FunctionAttributeType}(\"{handler.MethodName}\")]");

        switch (handler.Kind)
        {
            case HandlerKind.Http:
                BuildHttpHandlerMethod(builder, model, handler, model.Filters.AsArray().Length > 0);
                break;
            case HandlerKind.Timer:
                BuildTimerHandlerMethod(builder, model, handler, model.Filters.AsArray().Length > 0);
                break;
            case HandlerKind.Queue:
                BuildQueueHandlerMethod(builder, model, handler, model.Filters.AsArray().Length > 0);
                break;
        }
    }

    private static void BuildHttpHandlerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler, bool hasFilters)
    {
        var authLevel = $"global::Microsoft.Azure.Functions.Worker.AuthorizationLevel.{handler.AuthorizationLevel ?? "Function"}";
        var httpMethod = handler.HttpMethod ?? "get";
        var route = handler.Route ?? handler.MethodName;

        builder.AppendLine($"public static async global::System.Threading.Tasks.Task<{IActionResultType}> {handler.MethodName}_Handler(");
        builder.AppendLine($"    [{HttpTriggerType}({authLevel}, \"{httpMethod}\", Route = \"{route}\")] {HttpRequestType} req,");
        builder.AppendLine($"    {FunctionContextType} context)");
        builder.BeginBlock();

        if (hasFilters)
        {
            builder.AppendLine($"var ctx = new {InvocationContextType}");
            builder.BeginBlock();
            builder.AppendLine("Request = req,");
            builder.AppendLine("FunctionContext = context,");
            builder.AppendLine($"CancellationToken = {CancellationTokenExpr},");
            builder.EndBlock(semicolon: true);
            builder.NewLine();

            builder.AppendLine("try");
            builder.BeginBlock();
            builder.AppendLine($"await __{handler.MethodName}_Pipeline__(ctx);");
            builder.EndBlock();
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            builder.AppendLine($"return new {ObjectResultType}(ex.Message) {{ StatusCode = ex.StatusCode }};");
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception)");
            builder.BeginBlock();
            builder.AppendLine($"return new {StatusCodeResultType}(500);");
            builder.EndBlock();
            builder.NewLine();
            builder.AppendLine($"return ({IActionResultType})ctx.Result!;");
        }
        else
        {
            builder.AppendLine("try");
            builder.BeginBlock();
            BuildParameterBindings(builder, handler, hasFilter: false);
            BuildHandlerInvocation(builder, model, handler, hasFilter: false);
            builder.EndBlock();
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            builder.AppendLine($"return new {ObjectResultType}(ex.Message) {{ StatusCode = ex.StatusCode }};");
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception)");
            builder.BeginBlock();
            builder.AppendLine($"return new {StatusCodeResultType}(500);");
            builder.EndBlock();
        }

        builder.EndBlock();
    }

    private static void BuildTimerHandlerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler, bool hasFilters)
    {
        var schedule = handler.TimerSchedule ?? "0 * * * * *";

        builder.AppendLine($"public static async global::System.Threading.Tasks.Task {handler.MethodName}_Handler(");
        builder.AppendLine($"    [{TimerTriggerType}(\"{schedule}\")] {TimerInfoType} timerInfo,");
        builder.AppendLine($"    {FunctionContextType} context)");
        builder.BeginBlock();

        if (hasFilters)
        {
            builder.AppendLine($"var ctx = new {InvocationContextType}");
            builder.BeginBlock();
            builder.AppendLine("Request = timerInfo,");
            builder.AppendLine("FunctionContext = context,");
            builder.AppendLine($"CancellationToken = {CancellationTokenExpr},");
            builder.EndBlock(semicolon: true);
            builder.NewLine();
            builder.AppendLine("try");
            builder.BeginBlock();
            builder.AppendLine($"await __{handler.MethodName}_Pipeline__(ctx);");
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception)");
            builder.BeginBlock();
            builder.AppendLine("throw;");
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine("try");
            builder.BeginBlock();
            BuildTimerParameterBindings(builder, handler);
            BuildHandlerInvocation(builder, model, handler, hasFilter: false);
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception)");
            builder.BeginBlock();
            builder.AppendLine("throw;");
            builder.EndBlock();
        }

        builder.EndBlock();
    }

    private static void BuildQueueHandlerMethod(SourceBuilder builder, FunctionModel model, HandlerModel handler, bool hasFilters)
    {
        var queueName = handler.QueueName ?? "myqueue";
        var connectionPart = handler.QueueConnection != null ? $", Connection = \"{handler.QueueConnection}\"" : string.Empty;

        builder.AppendLine($"public static async global::System.Threading.Tasks.Task {handler.MethodName}_Handler(");
        builder.AppendLine($"    [{QueueTriggerType}(\"{queueName}\"{connectionPart})] string message,");
        builder.AppendLine($"    {FunctionContextType} context)");
        builder.BeginBlock();

        if (hasFilters)
        {
            builder.AppendLine($"var ctx = new {InvocationContextType}");
            builder.BeginBlock();
            builder.AppendLine("Request = message,");
            builder.AppendLine("FunctionContext = context,");
            builder.AppendLine($"CancellationToken = {CancellationTokenExpr},");
            builder.EndBlock(semicolon: true);
            builder.NewLine();
            builder.AppendLine("try");
            builder.BeginBlock();
            builder.AppendLine($"await __{handler.MethodName}_Pipeline__(ctx);");
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception)");
            builder.BeginBlock();
            builder.AppendLine("throw;");
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine("try");
            builder.BeginBlock();
            BuildQueueParameterBindings(builder, handler);
            BuildHandlerInvocation(builder, model, handler, hasFilter: false);
            builder.EndBlock();
            builder.AppendLine("catch (global::System.Exception)");
            builder.BeginBlock();
            builder.AppendLine("throw;");
            builder.EndBlock();
        }

        builder.EndBlock();
    }

    private static void BuildParameterBindings(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        var parameters = handler.Parameters.AsArray();
        for (var i = 0; i < parameters.Length; i++)
        {
            BuildParameterBinding(builder, handler, parameters[i], i, hasFilter);
        }
    }

    private static void BuildTimerParameterBindings(SourceBuilder builder, HandlerModel handler)
    {
        var parameters = handler.Parameters.AsArray();
        for (var i = 0; i < parameters.Length; i++)
        {
            var p = parameters[i];
            if (p.BindingKind == ParameterBindingKind.FromServices)
            {
                builder.AppendLine($"var p{i} = {GetRequiredService}<{p.Type.FullName}>(__provider__);");
                builder.NewLine();
            }
        }
    }

    private static void BuildQueueParameterBindings(SourceBuilder builder, HandlerModel handler)
    {
        var parameters = handler.Parameters.AsArray();
        for (var i = 0; i < parameters.Length; i++)
        {
            var p = parameters[i];
            if (p.BindingKind == ParameterBindingKind.FromServices)
            {
                builder.AppendLine($"var p{i} = {GetRequiredService}<{p.Type.FullName}>(__provider__);");
                builder.NewLine();
            }
        }
    }

    private static void BuildParameterBinding(SourceBuilder builder, HandlerModel handler, ParameterModel param, int index, bool hasFilter)
    {
        var pVar = $"p{index}";
        var typeName = param.Type.FullName;

        switch (param.BindingKind)
        {
            case ParameterBindingKind.HttpRequest:
            case ParameterBindingKind.FunctionContext:
            case ParameterBindingKind.CancellationToken:
            case ParameterBindingKind.Logger:
                return;
            case ParameterBindingKind.FromServices:
                builder.AppendLine($"var {pVar} = {GetRequiredService}<{typeName}>(__provider__);");
                builder.NewLine();
                return;
            case ParameterBindingKind.FromBody:
                builder.AppendLine($"var {pVar} = __bodySerializer__.Deserialize<{typeName}>(req.Body);");
                if (!param.SkipValidation)
                {
                    builder.AppendLine($"if ({pVar} is not null && !__requestValidator__.Validate({pVar}))");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = new {BadRequestResultType}(\"Validation failed: {param.Name}\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine($"return new {BadRequestResultType}(\"Validation failed: {param.Name}\");");
                    }
                    builder.EndBlock();
                }

                builder.NewLine();
                return;
            case ParameterBindingKind.FromQuery:
                BuildScalarOrArrayBinding(builder, param, index, hasFilter, "req.Query");
                return;
            case ParameterBindingKind.FromRoute:
                BuildRouteBinding(builder, param, index, hasFilter);
                return;
            case ParameterBindingKind.FromHeader:
                BuildHeaderBinding(builder, param, index, hasFilter);
                return;
        }
    }

    private static void BuildScalarOrArrayBinding(SourceBuilder builder, ParameterModel param, int index, bool hasFilter, string dictExpr)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var typeName = param.Type.FullName;
        var key = param.Key;
        var defaultLiteral = param.HasDefault ? (param.DefaultValueLiteral ?? "default") : null;

        if (param.Type.IsArray && (param.Type.ElementType != null))
        {
            var elemType = param.Type.ElementType.FullName;
            var converterMethod = param.ConverterMethod;
            builder.AppendLine($"var {pVar} = global::System.Array.Empty<{elemType}>();");
            builder.AppendLine($"if ({dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
            builder.BeginBlock();
            builder.AppendLine($"var {pVar}parts = {pRaw}.ToString().Split(',');");
            builder.AppendLine($"{pVar} = new {elemType}[{pVar}parts.Length];");
            builder.AppendLine($"for (var i = 0; i < {pVar}parts.Length; i++)");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar}[i] = {pVar}parts[i];");
            }
            else
            {
                var converterCall = $"!{StringConverterType}.TryConvert<{elemType}>({pVar}parts[i], out {pVar}[i])";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
            }

            builder.EndBlock();
            builder.EndBlock();
            builder.NewLine();
        }
        else if (param.Type.IsNullable && (param.Type.UnderlyingType != null))
        {
            var baseType = param.Type.UnderlyingType.FullName;
            var converterMethod = param.ConverterMethod;
            builder.AppendLine($"var {pVar} = ({typeName})null;");
            builder.AppendLine($"if ({dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw};");
            }
            else
            {
                var converterCall = $"!{StringConverterType}.TryConvert<{baseType}>({pRaw}.ToString(), out var {pVar}tmp)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar} = {pVar}tmp;");
            }

            builder.EndBlock();
            builder.NewLine();
        }
        else
        {
            var converterMethod = param.ConverterMethod;
            if (String.IsNullOrEmpty(converterMethod))
            {
                var init = defaultLiteral != null ? $"({typeName}){defaultLiteral}!" : $"default({typeName})!";
                builder.AppendLine($"var {pVar} = {init};");
                builder.AppendLine($"if ({dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
                builder.AppendLine($"    {pRaw} != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
                builder.BeginBlock();
                builder.AppendLine($"{pVar} = {pRaw}!;");
                builder.EndBlock();
                builder.NewLine();
            }
            else
            {
                var init = defaultLiteral != null ? $"({typeName}){defaultLiteral}" : $"default({typeName})";
                builder.AppendLine($"var {pVar} = {init};");
                builder.AppendLine($"if ({dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
                builder.AppendLine($"    {pRaw} != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
                builder.BeginBlock();
                var converterCall = $"!{StringConverterType}.TryConvert<{typeName}>({pRaw}.ToString(), out {pVar})";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
                builder.EndBlock();
                builder.NewLine();
            }
        }
    }

    private static void BuildRouteBinding(SourceBuilder builder, ParameterModel param, int index, bool hasFilter)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var typeName = param.Type.FullName;
        var key = param.Key;
        var converterMethod = param.ConverterMethod;

        if (param.Type.IsNullable && (param.Type.UnderlyingType != null))
        {
            var baseType = param.Type.UnderlyingType.FullName;
            builder.AppendLine($"var {pVar} = ({typeName})null;");
            builder.AppendLine($"if (req.RouteValues.TryGetValue(\"{key}\", out var {pRaw}obj) && {pRaw}obj is string {pRaw})");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw};");
            }
            else
            {
                var converterCall = $"!{StringConverterType}.TryConvert<{baseType}>({pRaw}, out var {pVar}tmp)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar} = {pVar}tmp;");
            }

            builder.EndBlock();
            builder.NewLine();
        }
        else
        {
            var defaultLiteral = param.HasDefault ? (param.DefaultValueLiteral ?? "default") : null;
            var init = defaultLiteral != null ? $"({typeName}){defaultLiteral}" : $"default({typeName})";
            builder.AppendLine($"var {pVar} = {init};");
            builder.AppendLine($"if (req.RouteValues.TryGetValue(\"{key}\", out var {pRaw}obj) && {pRaw}obj is string {pRaw})");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw}!;");
            }
            else
            {
                var converterCall = $"!{StringConverterType}.TryConvert<{typeName}>({pRaw}, out {pVar})";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
            }

            builder.EndBlock();
            builder.NewLine();
        }
    }

    private static void BuildHeaderBinding(SourceBuilder builder, ParameterModel param, int index, bool hasFilter)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var typeName = param.Type.FullName;
        var key = param.Key;
        var converterMethod = param.ConverterMethod;

        if (param.Type.IsNullable && (param.Type.UnderlyingType != null))
        {
            var baseType = param.Type.UnderlyingType.FullName;
            builder.AppendLine($"var {pVar} = ({typeName})null;");
            builder.AppendLine($"if (req.Headers.TryGetValue(\"{key}\", out var {pRaw}sv) &&");
            builder.AppendLine($"    {pRaw}sv != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
            builder.BeginBlock();
            builder.AppendLine($"var {pRaw} = {pRaw}sv.ToString();");
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw};");
            }
            else
            {
                var converterCall = $"!{StringConverterType}.TryConvert<{baseType}>({pRaw}, out var {pVar}tmp)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar} = {pVar}tmp;");
            }

            builder.EndBlock();
            builder.NewLine();
        }
        else
        {
            var defaultLiteral = param.HasDefault ? (param.DefaultValueLiteral ?? "default") : null;
            var init = String.IsNullOrEmpty(converterMethod)
                ? (defaultLiteral != null ? $"({typeName}){defaultLiteral}!" : $"default({typeName})!")
                : (defaultLiteral != null ? $"({typeName}){defaultLiteral}" : $"default({typeName})");
            builder.AppendLine($"var {pVar} = {init};");
            builder.AppendLine($"if (req.Headers.TryGetValue(\"{key}\", out var {pRaw}sv) &&");
            builder.AppendLine($"    {pRaw}sv != global::Microsoft.Extensions.Primitives.StringValues.Empty)");
            builder.BeginBlock();
            builder.AppendLine($"var {pRaw} = {pRaw}sv.ToString();");
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw}!;");
            }
            else
            {
                var converterCall = $"!{StringConverterType}.TryConvert<{typeName}>({pRaw}, out {pVar})";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine($"return new {BadRequestResultType}($\"Invalid parameter: {key}\");");
                }
                builder.EndBlock();
            }

            builder.EndBlock();
            builder.NewLine();
        }
    }

    private static void BuildHandlerInvocation(SourceBuilder builder, FunctionModel model, HandlerModel handler, bool hasFilter)
    {
        var args = BuildCallArgs(handler, hasFilter, model.ServiceResolver != null);
        var awaitPrefix = handler.IsAsync ? "await " : string.Empty;

        if (handler.Kind != HandlerKind.Http)
        {
            if (handler.ResultType != null)
            {
                builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({args});");
                if (hasFilter)
                {
                    builder.AppendLine("ctx.Result = __result__;");
                }
            }
            else
            {
                builder.AppendLine($"{awaitPrefix}__target__.{handler.MethodName}({args});");
            }

            return;
        }

        builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({args});");
        if (hasFilter)
        {
            builder.AppendLine("ctx.Result = __result__;");
        }
        else
        {
            builder.AppendLine("return __result__;");
        }
    }

    private static string BuildCallArgs(HandlerModel handler, bool hasFilter, bool hasProvider)
    {
        var parameters = handler.Parameters.AsArray();
        var argParts = new List<string>();

        for (var i = 0; i < parameters.Length; i++)
        {
            var p = parameters[i];
            switch (p.BindingKind)
            {
                case ParameterBindingKind.HttpRequest:
                    argParts.Add("req");
                    break;
                case ParameterBindingKind.FunctionContext:
                    argParts.Add(hasFilter ? "ctx.FunctionContext" : "context");
                    break;
                case ParameterBindingKind.CancellationToken:
                    argParts.Add(hasFilter ? "ctx.CancellationToken" : CancellationTokenExpr);
                    break;
                case ParameterBindingKind.Logger:
                    argParts.Add(hasProvider
                        ? $"{GetRequiredService}<{p.Type.FullName}>(__provider__)"
                        : "default!");
                    break;
                case ParameterBindingKind.FromTrigger:
                    argParts.Add(handler.Kind == HandlerKind.Timer ? "timerInfo" : "message");
                    break;
                default:
                    argParts.Add($"p{i}!");
                    break;
            }
        }

        return String.Join(", ", argParts);
    }

    private static string ToPascalCase(string name)
    {
        if (String.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }
}

internal static class SourceBuilderExtensions
{
    public static void AppendLine(this SourceBuilder builder, string line)
    {
        builder.Indent().Append(line).NewLine();
    }

    public static void BeginBlock(this SourceBuilder builder)
    {
        builder.Indent().Append("{").NewLine();
        builder.IndentLevel++;
    }

    public static void EndBlock(this SourceBuilder builder, bool semicolon = false)
    {
        builder.IndentLevel--;
        builder.Indent();
        if (semicolon)
        {
            builder.Append("};").NewLine();
        }
        else
        {
            builder.Append("}").NewLine();
        }
    }
}
