<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <NoWarn>$(NoWarn);NU5118;NU5129</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackBuildOutputs</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <Target Name="PackBuildOutputs" DependsOnTargets="SatelliteDllsProjectOutputGroup;DebugSymbolsProjectOutputGroup">
    <ItemGroup>
      <TfmSpecificPackageFile Include="..\AzureFunctionsExtension.Generator\bin\$(Configuration)\netstandard2.0\AzureFunctionsExtension.Generator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
      <TfmSpecificPackageFile Include="$(PKGSourceGenerateHelper)\lib\netstandard2.0\SourceGenerateHelper.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
      <TfmSpecificPackageFile Include="..\AzureFunctionsExtension.props" Pack="true" PackagePath="buildTransitive\AzureFunctionsExtension.props" Visible="false" />
      <TfmSpecificPackageFile Include="..\AzureFunctionsExtension.targets" Pack="true" PackagePath="buildTransitive\AzureFunctionsExtension.targets" Visible="false" />
    </ItemGroup>
  </Target>

  <PropertyGroup>
    <PackageId>AzureFunctionsExtension</PackageId>
    <Title>AzureFunctionsExtension</Title>
    <Description>Azure Functions extension.</Description>
    <PackageTags>azure functions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="SourceGenerateHelper" Version="1.24.0" GeneratePathProperty="true" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AzureFunctionsExtension.Generator\AzureFunctionsExtension.Generator.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>

</Project>
